"compreg" <- function(symbol,
                      tf.binding,
                      tf.name,
                      elem.name,
                      peak.gene.prior.path,
                      E1,
                      E1.idx,
                      E2,
                      E2.idx,
                      O1.mean,
                      O2.mean,
                      match.mat,
                      thresh,
                      sig.level,
                      num.top.tf,
                      d0.default,
                      verbose,
                      ...) {
    UseMethod("compreg")
}
