# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compReg <- function(O1, E1, O1Idx, E1Idx, symbol1, peakName1, O2, E2, O2Idx, E2Idx, symbol2, peakName2, peakNameIntersect) {
    .Call(`_scCompReg_compReg`, O1, E1, O1Idx, E1Idx, symbol1, peakName1, O2, E2, O2Idx, E2Idx, symbol2, peakName2, peakNameIntersect)
}

initializeMatrix <- function(POnRow, POnCol, XnCol, k, D) {
    .Call(`_scCompReg_initializeMatrix`, POnRow, POnCol, XnCol, k, D)
}

computeLambda <- function(PeakO, w1, h1, X, w2, h2, D, beta, alpha, eps) {
    .Call(`_scCompReg_computeLambda`, PeakO, w1, h1, X, w2, h2, D, beta, alpha, eps)
}

iterateCluster <- function(PeakO, X, D, k, maxIter, lambda1, lambda2, W10, H10, W20, H20, epsD, tolX, tolFun, verbose, loopUpdate) {
    .Call(`_scCompReg_iterateCluster`, PeakO, X, D, k, maxIter, lambda1, lambda2, W10, H10, W20, H20, epsD, tolX, tolFun, verbose, loopUpdate)
}

postLapMatMult <- function(W1, W2, H1, H2) {
    .Call(`_scCompReg_postLapMatMult`, W1, W2, H1, H2)
}

