# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loadPeakNameIntersectFile <- function(path, token) {
    .Call(`_scCompReg_loadPeakNameIntersectFile`, path, token)
}

threshK <- function(A, thresh) {
    .Call(`_scCompReg_threshK`, A, thresh)
}

mult <- function(A, B) {
    .Call(`_scCompReg_mult`, A, B)
}

colMax <- function(X) {
    .Call(`_scCompReg_colMax`, X)
}

mfbsLoad <- function(motifTargetPath) {
    .Call(`_scCompReg_mfbsLoad`, motifTargetPath)
}

corrTest <- function(X, Y) {
    .Call(`_scCompReg_corrTest`, X, Y)
}

accumArrayMin <- function(subs, val) {
    .Call(`_scCompReg_accumArrayMin`, subs, val)
}

computeBZ <- function(tfBinding, OM, beta) {
    .Call(`_scCompReg_computeBZ`, tfBinding, OM, beta)
}

compRegLoad <- function(peakGenePriorPath) {
    .Call(`_scCompReg_compRegLoad`, peakGenePriorPath)
}

initializeMatrix <- function(POnRow, POnCol, XnCol, k, D) {
    .Call(`_scCompReg_initializeMatrix`, POnRow, POnCol, XnCol, k, D)
}

computeLambda <- function(PeakO, w1, h1, X, w2, h2, D, alpha, beta, eps) {
    .Call(`_scCompReg_computeLambda`, PeakO, w1, h1, X, w2, h2, D, alpha, beta, eps)
}

iterateCluster <- function(PeakO, X, D, k, maxIter, lambda1, lambda2, W10, H10, W20, H20, tolX, tolFun, verbose, loopUpdate) {
    .Call(`_scCompReg_iterateCluster`, PeakO, X, D, k, maxIter, lambda1, lambda2, W10, H10, W20, H20, tolX, tolFun, verbose, loopUpdate)
}

cluster <- function(H1, H2) {
    .Call(`_scCompReg_cluster`, H1, H2)
}

postLapMatMult <- function(W1, W2, H1, H2) {
    .Call(`_scCompReg_postLapMatMult`, W1, W2, H1, H2)
}

