"sc_compreg" <- function(O1,
                         E1,
                         O1.idx,
                         E1.idx,
                         symbol1,
                         peak.name1,
                         O2,
                         E2,
                         O2.idx,
                         E2.idx,
                         symbol2,
                         peak.name2,
                         motif.name,
                         motif.weight,
                         match2,
                         peak.name.intersect.dir,
                         motif.target.dir,
                         peak.gene.prior.dir,
                         sep.char,
                         thresh,
                         sig.level,
                         num.top.tf,
                         d0.default,
                         verbose,
                         ...) {
    UseMethod("sc_compreg")
}
